secrets:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OHzNa3QYMwudRfYro4Iakmgg6l0=,iv:ezBL5c5sv8YrKTO0GsN35yFjkD3qHyxpCvHoFgn5Rxg=,tag:MqRg9P7ZuFa8CMUODl6RFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:klx81H/35Vy7s2F4X/tDFWm7W8bDNLdAfP3rG5R7bOpX0ad7ee+DUA==,iv:LTEmyxC0pVQZDnaLDJv4+AZ/68TXt44/CRVK28Yv8s0=,tag:elfnQG89029uHZ5FmSXXrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aHZ1RzU2L1dxWXFrNGhM
            WklDOCs0Y09LNGNyekdsWS9TaFMrK3JrQ1c0CkxZcS8yMks2UDNuaDEycE9zZzBD
            Z3BvNkNGN01LVkcxWDZBY24zOGhDMXcKLS0tIEJIdWc2RWo1eGRNaWl4QnJkQTdI
            Q1JCYmdUa1haZmdteG0xaDM3ZDYxSTgKH3w7/N/IcQLgcYEY0s0nJ+rjHHpZ70pm
            yxN96F4Hh/6WgdJBEuceF2KA3OWIxynqj/ult4+CG4f1a4xFHV5EYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
    lastmodified: "2026-09-18T13:59:02Z"
    mac: ENC[AES256_GCM,data:zL0SL5ujSsU1Ak08CD3qbqEdwEo5a94WTXpewuASwY7Z93wt/xu0ot7WfmrdGT+sqvBpMPkLuA7q9z88ABOf3TD0fyMTTF68LEK5/EVCS2Rk7BIg48oCPV49t6NZp7JDTnatJtiRutvomMF+iPc72/0sv3KVXcUgG6sjAzo12+k=,iv:aWLUtfMz/qn/bVnnvqkK31+u+MGwLxUSfDI0czZePPY=,tag:QAcX2CANTtv5O7zHpKjWlQ==,type:str]
    pgp:
        - created_at: "2026-09-18T13:59:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNryRZ+XfAgsSAQdAD3l+fpnGPr7/JEOwvt347IeW3dMlMbAeZ+TEL+4c8RQw
            yd1WEWq+jWOH82EpKyKeqD/nFoKPCKegVpsnPwfqYkSR5cRb1XUQnlLqobj+Vtkh
            0l4B6xYAWAyVKDrkvMAuE7NMsVAezMqb8F41Nia4KAQL9tpa4x27bikJAvQGleIx
            lD/JvwN6VVv98tEwQubmaNkN6xVcVLqQEQGHjusgvCDbnRffGgnLFlRB3zOSOSzp
            =Uavm
            -----END PGP MESSAGE-----
          fp: 4F8E31286D7997C9625C6F7B322C6F63F594CE7C
        - created_at: "2026-09-18T13:59:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdArVOd6t1dvCL8/XL1IyOiEhgwMk9QQEu80U83AlXua3Mw
            f2e/HuKbQBxwJrQaH4bqgVDasDg9PC6yV7gWFpNJq1voKRNjUe9ydRgzAijcgJC2
            0l4BFKdZ+5qHf9Q6Wwa4ytYIAH7Sxsw5FvAfcyjaZfKe53dgVjDyigI4jnEnS6Yx
            OrsLaRH3+DiaPUbdBp8DxUzBpEjxIYzc4TDNDHIIlGe7UZStrB7MFWtJ0yH10fXM
            =Drfb
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2026-09-18T13:59:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqqdQLSUqHusSAQdAKxauQO817GPy/fKHD7/D5tMmsnlwH6o6BMWKrrNX+jIw
            FhxWVFsdCwIavhcM9BNKZoyy0ePB3B9QDoEiXA+v62+corlF91nFJ6sxhp1JBpu8
            0l4BvFsBIl7y7CWDKqIR+P1pZEju4QMl3RejE5eS6hcz/8vRVF6f8CJ/r9Im9M3P
            kih9iJwOoQzkkWRLwIe2E6mACF+UheR7qmiLzVvgxYEKg1y5QONcHQtqssWzbQVF
            =xYiS
            -----END PGP MESSAGE-----
          fp: 77D901DDCB59376D9E4131279BAC0E08F5067BB8
        - created_at: "2026-09-18T13:59:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdAo4paK0F4NPbGo1xTmuWxRjvgdm/STdz8gpGwmtrv3HIw
            g1IOWSnpGjuQIrhNRb7Bxk9gy3ftY6+7F5a+CO5GTgqpek6Zlfkadb2hIbuUSHsk
            0l4BJgi6blefPki/v/KQwdNkV5TtbYQRCmbO/dbtRrJou/68IWs81wuWZYgRvo3h
            VQTsf92P20WO/vBoZFH9caYm6P5OFiw7Cck43t3Ee9ZKOMFuStqqogdWnJBicjO3
            =JJGD
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
    unencrypted_suffix: _unencrypted
    version: 3.13.3
