secrets:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AeXmU6IET6Mu1m7RrGbUxKYfeGw=,iv:ivTCvzsvlMDeRi1Xo+Xig+q/MFjinRT25oTQ4dTpD5w=,tag:ZgeWJ9306rFP2QCfn13XEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jOYsF4j5MuwJnUDW+m2TQxCaf1DOH+6QeAwtkBI2UKSCepG0ptHuzw==,iv:bYHZmQZly0S0fpRTQ6VwbafDYxH18jmfn6T/0/KQuqQ=,tag:55xc/fyBbb96QYzlohkZ+A==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:Q7KZm7eenYFn,iv:VuzTTfAHe9FOTcqrGiJU9qdNixTxszm23rSXuNDB3cA=,tag:eGbIm8M/1Lsl0aoa9NanOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb2pZN2o5TGhlLzFtcGhu
            ckU4d0dBM0o0WDNLTjRGdFAySjZSQTIzMW1ZCkIzOU9RUzJGREJ3L3BDMkdWSnhj
            ZWU1MzMyZ2NGZUt5aWN0MUk4dU1sUWcKLS0tIFhWTFdQTkhRdE16OVI5ZnpPMHZR
            dllybHExU05JQTZWSnVqbmJ6bHpSaWcKr/ZjKj4UzLIvXZNnsZHzFl6iBaPCJXPJ
            SGSqAEWj9CCnDnPdpmQ1bze4OkCrM9YSJth1RjmglYmAuiJtKnLMwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T11:53:09Z"
    mac: ENC[AES256_GCM,data:t2RCcXs9JRHPOcy8olzOSGNPvj0XeSafsBGnAFBAuh+UpQmTCCsSQt2XhacgYcyyUzDnjV2N0PtXM6WCwKay/gokMfQti+xBb0XCH80cdWn07Nk49JxPJLGijzR+uirxX+P8uEWXgqJHZN+gTOCEukrnmGCnPYkC0K/cwTZlk+o=,iv:qAw+fEqPARcUsg4kJq2xLg1uGj51zEaWTIuu51ZodCs=,tag:KGU8yFuuF5EoFiG8v1gJYQ==,type:str]
    pgp:
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/dYBJRlWfQISAQdAAmKo8+br2TDrHnmFeY1FXmRrHP9hkWBaKKhQhDB+6WAw
            HW64Q8eeoG9K2HAjILqUPy02GI+qqBS+Jjw8XHaQLdcGVMt+L3Re5cNAZ9lZG/1N
            0l4BwV9kf7wc1Og6ClSasDwjjt3sR4g3/rv9M68XHsRDbfPm2ac+NCoew/DR9id2
            3A8VQVQ7GDE7G19e2+Fud6egJt/JiJaosHacO/UYFD3Ocksgi2eacix8Tb2xjHWj
            =Pq8/
            -----END PGP MESSAGE-----
          fp: 15D5721F5F5BAF121495363EFE042E3D4085A811
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdAHH0pwGVdbNatbvEroZT/TUVKe1vfPA+i9sFcPrIniE8w
            MC5bzAXvHZGpa1ql6+7C+YYSSV+oON/eYVSjO3B9WXwEv7WlpTPujAvutixcz6sN
            0l4BFWFFqbwDZSdd/vLU1VXM2yihoOVvUdSMoP2nVJCz8AbArUEvFT/ssy5JuPC8
            oCwH3g0FVRaz0w8Lxldf28vZZ4PBYS3iOmsurawGldBvcBNth7mB/Eo6XuD0Q7v8
            =kKYr
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DCsA/BhMt3V4SAQdAkAmczPE1xQCCu+2St6giE6i29PQIUEWMq//9SpGP6How
            4x6zJqFdY435GZuU6/CTmpbYSFspelKP+mOH03bz5Kw8DGMvee1LIzxicrf4RPym
            0l4BczFb2gQJ5XCHBYIhUGZdmO7o2mCEMYIxGr6aI1tattvgLlA33Xpf4OAw1w1E
            mGeueMlbOgBqYux0EUpC0aIO9zMBAYzfX67lzVkFfMUOGEtyvKB75O4TYx26uUbB
            =Nuce
            -----END PGP MESSAGE-----
          fp: 4919F560F0D35F80CF382D76E084A2DF1143C14D
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdAiJT+nUIYQvw4W+sCPF+t5+I0ZKXddUTiA3a9/T163wQw
            UvdVZBTf/Oc7lsK03ETyYSw5mOSiAs5bMNrJzUrZ/cEX/XbzVu0lSYPlAx1XvZQJ
            1GgBCQIQPoTwfaoqm77Be4kEutbEEW/W4lgDb31c8ddkMMyYu3rZZHXOsz+aDHhn
            VlBEw7IUxsS7rZy6eY+vzP2fyiHDkfAI2TJvMtoLL31KVXiyuB2jtB9eghSGx5A2
            nzKFiNhUcBUJvg==
            =ntfp
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvbozpGPUDxgSAQdAa3B0crOttxIBTMVyt/bNWQLi1EIKpHLhNk6RG0sgSEsw
            3UFWPdPpdlOdDSzr7hu9gaT3BvGlogh7+2jgaQK8fb92mPaQCk1fVextvyxwV2cj
            0l4B4zNqMZE5OE82AFJNQd4w3/KmApZsMilJNpncfcE+gvxsKGPBjYXF+mFZCuse
            lnWPlDS+u07ilGuiV4eNjZonT2gWFR2R1rLM1uYM0VEfnt+VGJLhUNvkrNRaYvAQ
            =FXo8
            -----END PGP MESSAGE-----
          fp: 5D7964FF2DB426ACB3C3505AA2A702DD5B689F45
        - created_at: "2025-05-14T09:47:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D44lO7/xrMMASAQdAfsBE4uDNn/w42a2PcWJB8Ar19o5zc465ra/4qPliJWMw
            9UU0tGK/VIjfPnqkkuDpaRxCRCMVpXc8HQJfgTuu+aTbtXDiCIH5bilxOSlJafSJ
            1GgBCQIQYUD4QdufvhPuM7gomYeRrXwx7LL04shxNd3FaDtyvrNcx3xgrrzL8Ue9
            TiHC5Ok84/zMgK9oWjhZxRv1iEEMrk09QigI83jwQ7JWy0KIh0ioW868ucWsrvaI
            kH5KUnyh95CIng==
            =QozW
            -----END PGP MESSAGE-----
          fp: E77ED9F8451E10BD242D07415444881046F92733
    unencrypted_suffix: _unencrypted
    version: 3.10.1
