secrets:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AeXmU6IET6Mu1m7RrGbUxKYfeGw=,iv:ivTCvzsvlMDeRi1Xo+Xig+q/MFjinRT25oTQ4dTpD5w=,tag:ZgeWJ9306rFP2QCfn13XEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jOYsF4j5MuwJnUDW+m2TQxCaf1DOH+6QeAwtkBI2UKSCepG0ptHuzw==,iv:bYHZmQZly0S0fpRTQ6VwbafDYxH18jmfn6T/0/KQuqQ=,tag:55xc/fyBbb96QYzlohkZ+A==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:Q7KZm7eenYFn,iv:VuzTTfAHe9FOTcqrGiJU9qdNixTxszm23rSXuNDB3cA=,tag:eGbIm8M/1Lsl0aoa9NanOQ==,type:str]
sops:
    age:
        - recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcFdwc0JTcGJISmlEYVpH
            ajJmOXUybkJaeWpBVzdaZjExcmRpUTBwVlNvClZMZzNhc3g1bVVqd1YvWlZOUGIw
            dm04WnZLVUV2dzBsM0xISm9Kc1FGNlEKLS0tIG4xSUJvUHloTUNLZGJUbjhKYmI2
            aGRDNzBvb09ZMnFXYjQyQ01VT3JWTkUKlxoDwPBcNAeXTy+qGg7QI7mZAV7bKEWT
            XGqFTGipHlZ3fLG8dqlSPGXVmy3rSyCkKJgvgbQNut4UMZtZSjXe5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T11:53:09Z"
    mac: ENC[AES256_GCM,data:t2RCcXs9JRHPOcy8olzOSGNPvj0XeSafsBGnAFBAuh+UpQmTCCsSQt2XhacgYcyyUzDnjV2N0PtXM6WCwKay/gokMfQti+xBb0XCH80cdWn07Nk49JxPJLGijzR+uirxX+P8uEWXgqJHZN+gTOCEukrnmGCnPYkC0K/cwTZlk+o=,iv:qAw+fEqPARcUsg4kJq2xLg1uGj51zEaWTIuu51ZodCs=,tag:KGU8yFuuF5EoFiG8v1gJYQ==,type:str]
    pgp:
        - created_at: "2024-12-26T15:24:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/dYBJRlWfQISAQdAhMxf2ufyvBjHsiYgVmxfyhpVjXIkAWOBPF0V2hTBchIw
            ty3hraRX8sRSyH9LBzO33xzsXYQH1XdynPy/xUSvSJ614GhOerDaDB2xKdLKhEaZ
            0l4BiT6s981bohkSBzxP6pqQc1EPsiXHt7VWdegq8c4egnluANr5iXcN0xuIb487
            HueNPaKXK6ZBF9QP+09tSNP6aAenejleCUHit2oM7afYIOy56UAi5Y3wMpIPy/zB
            =d88N
            -----END PGP MESSAGE-----
          fp: 15D5721F5F5BAF121495363EFE042E3D4085A811
        - created_at: "2024-12-26T15:24:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdATrXte4QAtZXgF8VY/Kfjqp243m4fj9CpJOf2GKbO+x0w
            xmVbY3h0iQogyvkYp3Us09qcYH5FsISkjxxIIIs4YB74kOwW6MvW4+BMfsnJUTzW
            0l4BHzdtU4m8JGqXOeP8C2BF0U22xaYGZMPPsextok3GjDNgNec1/4w7liWDehw8
            ORJ8z+15TxHyqoUnt4PWer5LOtE12f+MKGmDeOVxep/lSzZxrNycZCSLgaG5Cgdv
            =BgJM
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2024-12-26T15:24:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DCsA/BhMt3V4SAQdAENZRSE5wcxMS36LyYIlyIRj2IZR3gwn6vmpDPwcF3Ckw
            4Q7IAwgsSVTYloEq2L1ti6YiSYOIHJ6sQ37zb8MqjpnCwqeF+Ilw2zN6a4uapTDw
            0l4BEf2niBLKRnv4gYGAvQlsmDvKxD+XZgCA0Mf4Zo0gTBTNS5TRHaQuH2T+kZwc
            fMAy22upXAJErldINHQLctOwG0r45lpqJAHu5BbmDOoyrrvU9oBk253XMgopYWmG
            =WlAR
            -----END PGP MESSAGE-----
          fp: 4919F560F0D35F80CF382D76E084A2DF1143C14D
        - created_at: "2024-12-26T15:24:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdAaWSu41JqARDdez39dRCn2zP7TbiN/S+5yFsQvjohonsw
            RGgwTfrUVWy4E67EMx7RN3sVEXtLDBpBobdKOvUTqe6fZ+TSrqyalfDrlMDxaGjj
            1GgBCQIQYCBiEZ2BvxY654zbUVkEet2nm41Lg/qQsEqBnXXZT24hX85WUbOyAYct
            bR3sQZul9RlBFrkEXSLwBN+tFzidoIiHkHtRRsLZyCGKFfxyguM9He9CevDpggPA
            wkKtYzMUzrNfKw==
            =8JBm
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
        - created_at: "2024-12-26T15:24:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DzfZC0UNQ1VgSAQdAT6ORCIjbdFHRpTcZLEJIniYNWnkgB6kbOTUR7Z4TNyww
            YjqSVzt0pRHA0tnLKxC0EE1E9VGTrFjDpg0+yeoOzgS5M2zdl47LM9RMJTnA3cGM
            1GgBCQIQNQoVBm+zPbJstZMPWUO7vrgTRxKFREm9RW3y1UP4DO4MmMr1F6yJyN/Z
            0xZraVpL4YAj5FFnf9YkrPlTbiJsClO20k30rK79IEuXGkxTvLk4R0p8bbG1ps4D
            HaTBqg+N24qQ8w==
            =x4Lm
            -----END PGP MESSAGE-----
          fp: AA5213AF261C1977AF38B03A94B473337258BFD5
    unencrypted_suffix: _unencrypted
    version: 3.10.1
