//go:build !ignore_autogenerated

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneConfig) DeepCopyInto(out *ControlPlaneConfig) {
	*out = *in
	in.InitConfig.DeepCopyInto(&out.InitConfig)
	in.ControlPlaneConfig.DeepCopyInto(&out.ControlPlaneConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneConfig.
func (in *ControlPlaneConfig) DeepCopy() *ControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineNamingStrategy) DeepCopyInto(out *MachineNamingStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineNamingStrategy.
func (in *MachineNamingStrategy) DeepCopy() *MachineNamingStrategy {
	if in == nil {
		return nil
	}
	out := new(MachineNamingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdate) DeepCopyInto(out *RollingUpdate) {
	*out = *in
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdate.
func (in *RollingUpdate) DeepCopy() *RollingUpdate {
	if in == nil {
		return nil
	}
	out := new(RollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlane) DeepCopyInto(out *TalosControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlane.
func (in *TalosControlPlane) DeepCopy() *TalosControlPlane {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneDeprecatedStatus) DeepCopyInto(out *TalosControlPlaneDeprecatedStatus) {
	*out = *in
	if in.V1Beta1 != nil {
		in, out := &in.V1Beta1, &out.V1Beta1
		*out = new(TalosControlPlaneV1Beta1DeprecatedStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneDeprecatedStatus.
func (in *TalosControlPlaneDeprecatedStatus) DeepCopy() *TalosControlPlaneDeprecatedStatus {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneDeprecatedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneInitializationStatus) DeepCopyInto(out *TalosControlPlaneInitializationStatus) {
	*out = *in
	if in.ControlPlaneInitialized != nil {
		in, out := &in.ControlPlaneInitialized, &out.ControlPlaneInitialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneInitializationStatus.
func (in *TalosControlPlaneInitializationStatus) DeepCopy() *TalosControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneList) DeepCopyInto(out *TalosControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneList.
func (in *TalosControlPlaneList) DeepCopy() *TalosControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneMachineTemplate) DeepCopyInto(out *TalosControlPlaneMachineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneMachineTemplate.
func (in *TalosControlPlaneMachineTemplate) DeepCopy() *TalosControlPlaneMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneMachineTemplateDeletionSpec) DeepCopyInto(out *TalosControlPlaneMachineTemplateDeletionSpec) {
	*out = *in
	if in.NodeDrainTimeoutSeconds != nil {
		in, out := &in.NodeDrainTimeoutSeconds, &out.NodeDrainTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.NodeVolumeDetachTimeoutSeconds != nil {
		in, out := &in.NodeVolumeDetachTimeoutSeconds, &out.NodeVolumeDetachTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.NodeDeletionTimeoutSeconds != nil {
		in, out := &in.NodeDeletionTimeoutSeconds, &out.NodeDeletionTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneMachineTemplateDeletionSpec.
func (in *TalosControlPlaneMachineTemplateDeletionSpec) DeepCopy() *TalosControlPlaneMachineTemplateDeletionSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneMachineTemplateDeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneMachineTemplateSpec) DeepCopyInto(out *TalosControlPlaneMachineTemplateSpec) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
	if in.ReadinessGates != nil {
		in, out := &in.ReadinessGates, &out.ReadinessGates
		*out = make([]v1beta2.MachineReadinessGate, len(*in))
		copy(*out, *in)
	}
	in.Deletion.DeepCopyInto(&out.Deletion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneMachineTemplateSpec.
func (in *TalosControlPlaneMachineTemplateSpec) DeepCopy() *TalosControlPlaneMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneSpec) DeepCopyInto(out *TalosControlPlaneSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	if in.MachineNamingStrategy != nil {
		in, out := &in.MachineNamingStrategy, &out.MachineNamingStrategy
		*out = new(MachineNamingStrategy)
		**out = **in
	}
	in.ControlPlaneConfig.DeepCopyInto(&out.ControlPlaneConfig)
	if in.RolloutStrategy != nil {
		in, out := &in.RolloutStrategy, &out.RolloutStrategy
		*out = new(RolloutStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneSpec.
func (in *TalosControlPlaneSpec) DeepCopy() *TalosControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneStatus) DeepCopyInto(out *TalosControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
	if in.UpToDateReplicas != nil {
		in, out := &in.UpToDateReplicas, &out.UpToDateReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Deprecated != nil {
		in, out := &in.Deprecated, &out.Deprecated
		*out = new(TalosControlPlaneDeprecatedStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneStatus.
func (in *TalosControlPlaneStatus) DeepCopy() *TalosControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplate) DeepCopyInto(out *TalosControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplate.
func (in *TalosControlPlaneTemplate) DeepCopy() *TalosControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateList) DeepCopyInto(out *TalosControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateList.
func (in *TalosControlPlaneTemplateList) DeepCopy() *TalosControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TalosControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateMachineTemplate) DeepCopyInto(out *TalosControlPlaneTemplateMachineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateMachineTemplate.
func (in *TalosControlPlaneTemplateMachineTemplate) DeepCopy() *TalosControlPlaneTemplateMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateMachineTemplateSpec) DeepCopyInto(out *TalosControlPlaneTemplateMachineTemplateSpec) {
	*out = *in
	in.Deletion.DeepCopyInto(&out.Deletion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateMachineTemplateSpec.
func (in *TalosControlPlaneTemplateMachineTemplateSpec) DeepCopy() *TalosControlPlaneTemplateMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateResource) DeepCopyInto(out *TalosControlPlaneTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateResource.
func (in *TalosControlPlaneTemplateResource) DeepCopy() *TalosControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateResourceSpec) DeepCopyInto(out *TalosControlPlaneTemplateResourceSpec) {
	*out = *in
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	if in.MachineNamingStrategy != nil {
		in, out := &in.MachineNamingStrategy, &out.MachineNamingStrategy
		*out = new(MachineNamingStrategy)
		**out = **in
	}
	in.ControlPlaneConfig.DeepCopyInto(&out.ControlPlaneConfig)
	if in.RolloutStrategy != nil {
		in, out := &in.RolloutStrategy, &out.RolloutStrategy
		*out = new(RolloutStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateResourceSpec.
func (in *TalosControlPlaneTemplateResourceSpec) DeepCopy() *TalosControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneTemplateSpec) DeepCopyInto(out *TalosControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneTemplateSpec.
func (in *TalosControlPlaneTemplateSpec) DeepCopy() *TalosControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosControlPlaneV1Beta1DeprecatedStatus) DeepCopyInto(out *TalosControlPlaneV1Beta1DeprecatedStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta2.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosControlPlaneV1Beta1DeprecatedStatus.
func (in *TalosControlPlaneV1Beta1DeprecatedStatus) DeepCopy() *TalosControlPlaneV1Beta1DeprecatedStatus {
	if in == nil {
		return nil
	}
	out := new(TalosControlPlaneV1Beta1DeprecatedStatus)
	in.DeepCopyInto(out)
	return out
}
