// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// +kubebuilder:object:generate=true
// +groupName=controlplane.cluster.x-k8s.io
package v1alpha3

import clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"

// Conditions and condition Reasons for the TalosControlPlane object

const (
	// MachinesAllReadyCondition reports an aggregate of current status of the machines controlled by the TalosControlPlane.
	MachinesAllReadyCondition clusterv1.ConditionType = "MachinesAllReady"
)

const (
	// MachinesBootstrapped is tracking control planes bootstrap status.
	MachinesBootstrapped clusterv1.ConditionType = "MachinesBootstrapped"

	// WaitingForMachinesReason (Severity=Info) documents a TalosControlPlane bootstrap is waiting
	// for all control plane nodes to be created.
	WaitingForMachinesReason = "WaitingForMachines"

	// MachinesBootstrappedReason documents that all control plane machines have been bootstrapped.
	MachinesBootstrappedReason = "MachinesBootstrapped"
)

const (
	// AvailableCondition documents that the first control plane instance has completed Talos boot sequence
	// and so the control plane is available and an API server instance is ready for processing requests.
	AvailableCondition clusterv1.ConditionType = "Available"

	// WaitingForTalosBootReason (Severity=Info) documents a TalosControlPlane object waiting for the first
	// control plane instance to complete Talos boot sequence.
	WaitingForTalosBootReason = "WaitingForTalosBoot"

	// InvalidControlPlaneConfigReason (Severity=Error) documents that controlplane config is invalid and the provider
	// can not proceed with the bootstrap.
	InvalidControlPlaneConfigReason = "InvalidControlPlaneConfig"

	// AvailableReason documents that the TalosControlPlane is available.
	AvailableReason = "Available"
)

const (
	// MachinesSpecUpToDateCondition documents that the spec of the machines controlled by the TalosControlPlane
	// is up to date. When this condition is false, the TalosControlPlane is executing a rolling upgrade.
	MachinesSpecUpToDateCondition clusterv1.ConditionType = "MachinesSpecUpToDate"

	// RollingUpdateInProgressReason (Severity=Warning) documents a TalosControlPlane object executing a
	// rolling upgrade for aligning the machines spec to the desired state.
	RollingUpdateInProgressReason = "RollingUpdateInProgress"

	// MachinesSpecUpToDateReason documents that the spec of all machines controlled by the TalosControlPlane is up to date.
	MachinesSpecUpToDateReason = "MachinesSpecUpToDate"
)

const (
	// ResizedCondition documents a TalosControlPlane that is resizing the set of controlled machines.
	ResizedCondition clusterv1.ConditionType = "Resized"

	// ScalingUpReason (Severity=Info) documents a TalosControlPlane that is increasing the number of replicas.
	ScalingUpReason = "ScalingUp"

	// ScalingDownReason (Severity=Info) documents a TalosControlPlane that is decreasing the number of replicas.
	ScalingDownReason = "ScalingDown"

	// ResizedReason documents that the TalosControlPlane has reached the desired number of replicas.
	ResizedReason = "Resized"
)

const (
	// ControlPlaneComponentsHealthyCondition reports the overall status of control plane components
	// implemented as static pods generated by Talos including kube-api-server, kube-controller manager,
	// kube-scheduler and etcd.
	ControlPlaneComponentsHealthyCondition clusterv1.ConditionType = "ControlPlaneComponentsHealthy"

	// ControlPlaneComponentsUnhealthyReason (Severity=Error) documents a control plane component not healthy.
	ControlPlaneComponentsUnhealthyReason = "ControlPlaneComponentsUnhealthy"

	// ControlPlaneComponentsInspectionFailedReason documents a failure in inspecting the control plane component status.
	ControlPlaneComponentsInspectionFailedReason = "ControlPlaneComponentsInspectionFailed"

	// ControlPlaneComponentsHealthyReason documents that all control plane components are healthy.
	ControlPlaneComponentsHealthyReason = "ControlPlaneComponentsHealthy"
)

const (
	// EtcdClusterHealthyCondition documents the overall etcd cluster's health.
	EtcdClusterHealthyCondition clusterv1.ConditionType = "EtcdClusterHealthyCondition"

	// EtcdClusterUnhealthyReason (Severity=Error) is set when the etcd cluster is unhealthy.
	EtcdClusterUnhealthyReason = "EtcdClusterUnhealthy"

	// EtcdClusterHealthyReason documents that the etcd cluster is healthy.
	EtcdClusterHealthyReason = "EtcdClusterHealthy"
)

const (
	// MachinesCreatedCondition documents that the machines controlled by the TalosControlPlane are created.
	// When this condition is false, it indicates that there was an error when cloning the infrastructure/bootstrap template or
	// when generating the machine object.
	MachinesCreatedCondition clusterv1.ConditionType = "MachinesCreated"

	// InfrastructureTemplateCloningFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// clone the infrastructure template.
	InfrastructureTemplateCloningFailedReason = "InfrastructureTemplateCloningFailed"

	// BootstrapTemplateCloningFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// clone the bootstrap template.
	BootstrapTemplateCloningFailedReason = "BootstrapTemplateCloningFailed"

	// MachineGenerationFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// generate a machine object.
	MachineGenerationFailedReason = "MachineGenerationFailed"

	// MachinesCreatedReason documents that the TalosControlPlane has successfully created all required machines.
	MachinesCreatedReason = "MachinesCreated"
)
