// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package v1alpha3

import (
	"errors"
	"fmt"
	"reflect"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachineryconversion "k8s.io/apimachinery/pkg/conversion"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/utils/ptr"
	clusterv1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	utilconversion "sigs.k8s.io/cluster-api/util/conversion"
	"sigs.k8s.io/controller-runtime/pkg/conversion"

	cpv1beta1 "github.com/siderolabs/cluster-api-control-plane-provider-talos/api/v1beta1"
)

// apiVersionGetter resolves a contract-versioned apiGroup/kind to a fully qualified apiVersion.
// The controller is expected to inject a getter at startup using SetAPIVersionGetter; the default
// implementation fails so misconfiguration is caught early.
var apiVersionGetter = func(_ schema.GroupKind) (string, error) {
	return "", errors.New("apiVersionGetter not set")
}

// SetAPIVersionGetter wires the function used to resolve a contract-versioned reference back to a
// fully qualified apiVersion when down-converting to v1alpha3.
func SetAPIVersionGetter(f func(gk schema.GroupKind) (string, error)) {
	apiVersionGetter = f
}

// ConvertTo converts this TalosControlPlane to the Hub version (v1beta1).
func (src *TalosControlPlane) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*cpv1beta1.TalosControlPlane)
	if err := Convert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(src, dst, nil); err != nil {
		return err
	}

	if src.Spec.InfrastructureTemplate.Name != "" {
		infraRef, err := convertToContractVersionedObjectReference(&src.Spec.InfrastructureTemplate)
		if err != nil {
			return err
		}
		dst.Spec.MachineTemplate.Spec.InfrastructureRef = *infraRef
	}

	// Manually restore data.
	restored := &cpv1beta1.TalosControlPlane{}
	ok, err := utilconversion.UnmarshalData(src, restored)
	if err != nil {
		return err
	}

	// Recover intent for bool values converted to *bool.
	initialization := cpv1beta1.TalosControlPlaneInitializationStatus{}
	var restoredControlPlaneInitialized *bool
	if ok {
		restoredControlPlaneInitialized = restored.Status.Initialization.ControlPlaneInitialized
	}
	clusterv1.Convert_bool_To_Pointer_bool(src.Status.Initialized, ok, restoredControlPlaneInitialized, &initialization.ControlPlaneInitialized)
	if !reflect.DeepEqual(initialization, cpv1beta1.TalosControlPlaneInitializationStatus{}) {
		dst.Status.Initialization = initialization
	}

	// Recover hub-only fields preserved via the data annotation.
	if ok {
		dst.Spec.MachineNamingStrategy = restored.Spec.MachineNamingStrategy
		dst.Spec.MachineTemplate.ObjectMeta = restored.Spec.MachineTemplate.ObjectMeta
		dst.Spec.MachineTemplate.Spec.ReadinessGates = restored.Spec.MachineTemplate.Spec.ReadinessGates
		dst.Spec.MachineTemplate.Spec.Deletion = restored.Spec.MachineTemplate.Spec.Deletion
		dst.Status.AvailableReplicas = restored.Status.AvailableReplicas
		dst.Status.UpToDateReplicas = restored.Status.UpToDateReplicas
	}

	return nil
}

// ConvertFrom converts from the Hub version (v1beta1) to this version (v1alpha3).
func (dst *TalosControlPlane) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*cpv1beta1.TalosControlPlane)
	if err := Convert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(src, dst, nil); err != nil {
		return err
	}

	if src.Spec.MachineTemplate.Spec.InfrastructureRef.IsDefined() {
		infraRef, err := convertToObjectReference(&src.Spec.MachineTemplate.Spec.InfrastructureRef, src.Namespace)
		if err != nil {
			return err
		}
		dst.Spec.InfrastructureTemplate = *infraRef
	}

	// Preserve Hub data on down-conversion.
	return utilconversion.MarshalData(src, dst)
}

func (src *TalosControlPlaneList) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*cpv1beta1.TalosControlPlaneList)
	return Convert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList(src, dst, nil)
}

func (dst *TalosControlPlaneList) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*cpv1beta1.TalosControlPlaneList)
	return Convert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList(src, dst, nil)
}

// Convert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec wraps the autogenerated
// converter. The InfrastructureTemplate ↔ MachineTemplate.Spec.InfrastructureRef remap is handled
// in ConvertTo because it requires access to the cluster-wide apiVersion getter.
func Convert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec(in *TalosControlPlaneSpec, out *cpv1beta1.TalosControlPlaneSpec, s apimachineryconversion.Scope) error {
	return autoConvert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec(in, out, s)
}

// Convert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec wraps the autogenerated
// converter. MachineTemplate / MachineNamingStrategy hub data is restored via the round-trip
// annotation in ConvertFrom.
func Convert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec(in *cpv1beta1.TalosControlPlaneSpec, out *TalosControlPlaneSpec, s apimachineryconversion.Scope) error {
	return autoConvert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec(in, out, s)
}

func Convert_v1alpha3_TalosControlPlaneStatus_To_v1beta1_TalosControlPlaneStatus(in *TalosControlPlaneStatus, out *cpv1beta1.TalosControlPlaneStatus, s apimachineryconversion.Scope) error {
	if err := autoConvert_v1alpha3_TalosControlPlaneStatus_To_v1beta1_TalosControlPlaneStatus(in, out, s); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta1 contract conditions should not automatically be converted into v1beta2 contract conditions.
	out.Conditions = nil

	// Retrieve new conditions (v1beta2) from the v1beta2 field.
	if in.V1Beta2 != nil {
		out.Conditions = in.V1Beta2.Conditions
	}

	// Move legacy conditions, failureReason, failureMessage and replica counters to the deprecated field.
	if out.Deprecated == nil {
		out.Deprecated = &cpv1beta1.TalosControlPlaneDeprecatedStatus{}
	}
	if out.Deprecated.V1Beta1 == nil {
		out.Deprecated.V1Beta1 = &cpv1beta1.TalosControlPlaneV1Beta1DeprecatedStatus{}
	}
	if in.Conditions != nil {
		clusterv1beta1.Convert_v1beta1_Conditions_To_v1beta2_Deprecated_V1Beta1_Conditions(&in.Conditions, &out.Deprecated.V1Beta1.Conditions)
	}
	out.Deprecated.V1Beta1.FailureReason = in.FailureReason
	out.Deprecated.V1Beta1.FailureMessage = in.FailureMessage
	out.Deprecated.V1Beta1.UnavailableReplicas = in.UnavailableReplicas
	out.Deprecated.V1Beta1.Initialized = in.Initialized
	out.Deprecated.V1Beta1.Ready = in.Ready

	// Move initialization to ControlPlaneInitialized; ConvertTo refines the bool intent against
	// the restored hub data.
	if in.Initialized {
		out.Initialization.ControlPlaneInitialized = ptr.To(true)
	}

	return nil
}

func Convert_v1beta1_TalosControlPlaneStatus_To_v1alpha3_TalosControlPlaneStatus(in *cpv1beta1.TalosControlPlaneStatus, out *TalosControlPlaneStatus, s apimachineryconversion.Scope) error {
	if err := autoConvert_v1beta1_TalosControlPlaneStatus_To_v1alpha3_TalosControlPlaneStatus(in, out, s); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta2 contract conditions should not automatically be converted into legacy conditions.
	out.Conditions = nil

	// Retrieve legacy conditions (v1beta1), failureReason, failureMessage and replica counters from the deprecated field.
	if in.Deprecated != nil && in.Deprecated.V1Beta1 != nil {
		if in.Deprecated.V1Beta1.Conditions != nil {
			clusterv1beta1.Convert_v1beta2_Deprecated_V1Beta1_Conditions_To_v1beta1_Conditions(&in.Deprecated.V1Beta1.Conditions, &out.Conditions)
		}
		out.FailureReason = in.Deprecated.V1Beta1.FailureReason
		out.FailureMessage = in.Deprecated.V1Beta1.FailureMessage
		out.UnavailableReplicas = in.Deprecated.V1Beta1.UnavailableReplicas
		out.Ready = in.Deprecated.V1Beta1.Ready
		out.Initialized = in.Deprecated.V1Beta1.Initialized
	} else {
		// Fallback when the deprecated holder is absent (older hub data): synthesize
		// ready from replica counts and initialized from Initialization.ControlPlaneInitialized.
		out.Ready = out.ReadyReplicas > 0
		out.Initialized = ptr.Deref(in.Initialization.ControlPlaneInitialized, false)
	}

	// Move new conditions (v1beta2) to the v1beta2 field.
	if in.Conditions == nil {
		return nil
	}
	out.V1Beta2 = &TalosControlPlaneV1Beta2Status{}
	out.V1Beta2.Conditions = in.Conditions

	return nil
}

// Implement local conversion func because conversion-gen is not aware of conversion func in other
// packages (see https://github.com/kubernetes/code-generator/issues/94).

func Convert_v1beta1_Condition_To_v1_Condition(in *clusterv1beta1.Condition, out *metav1.Condition, s apimachineryconversion.Scope) error {
	return clusterv1beta1.Convert_v1beta1_Condition_To_v1_Condition(in, out, s)
}

func Convert_v1_Condition_To_v1beta1_Condition(in *metav1.Condition, out *clusterv1beta1.Condition, s apimachineryconversion.Scope) error {
	return clusterv1beta1.Convert_v1_Condition_To_v1beta1_Condition(in, out, s)
}

func Convert_v1_ObjectReference_To_v1beta2_ContractVersionedObjectReference(_ *corev1.ObjectReference, _ *clusterv1.ContractVersionedObjectReference, _ apimachineryconversion.Scope) error {
	// Implemented in ConvertTo where the apiVersionGetter is available.
	return nil
}

func Convert_v1beta2_ContractVersionedObjectReference_To_v1_ObjectReference(_ *clusterv1.ContractVersionedObjectReference, _ *corev1.ObjectReference, _ apimachineryconversion.Scope) error {
	// Implemented in ConvertFrom where the apiVersionGetter is available.
	return nil
}

func convertToContractVersionedObjectReference(ref *corev1.ObjectReference) (*clusterv1.ContractVersionedObjectReference, error) {
	var apiGroup string
	if ref.APIVersion != "" {
		gv, err := schema.ParseGroupVersion(ref.APIVersion)
		if err != nil {
			return nil, fmt.Errorf("failed to convert object: failed to parse apiVersion: %v", err)
		}
		apiGroup = gv.Group
	}
	return &clusterv1.ContractVersionedObjectReference{
		APIGroup: apiGroup,
		Kind:     ref.Kind,
		Name:     ref.Name,
	}, nil
}

func convertToObjectReference(ref *clusterv1.ContractVersionedObjectReference, namespace string) (*corev1.ObjectReference, error) {
	apiVersion, err := apiVersionGetter(schema.GroupKind{
		Group: ref.APIGroup,
		Kind:  ref.Kind,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to convert object: %v", err)
	}
	return &corev1.ObjectReference{
		APIVersion: apiVersion,
		Kind:       ref.Kind,
		Namespace:  namespace,
		Name:       ref.Name,
	}, nil
}
