//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1beta1 "github.com/siderolabs/cluster-api-control-plane-provider-talos/api/v1beta1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	v1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*v1beta1.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*v1beta1.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig(a.(*v1beta1.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpdate)(nil), (*v1beta1.RollingUpdate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_RollingUpdate_To_v1beta1_RollingUpdate(a.(*RollingUpdate), b.(*v1beta1.RollingUpdate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RollingUpdate)(nil), (*RollingUpdate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpdate_To_v1alpha3_RollingUpdate(a.(*v1beta1.RollingUpdate), b.(*RollingUpdate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RolloutStrategy)(nil), (*v1beta1.RolloutStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_RolloutStrategy_To_v1beta1_RolloutStrategy(a.(*RolloutStrategy), b.(*v1beta1.RolloutStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RolloutStrategy)(nil), (*RolloutStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RolloutStrategy_To_v1alpha3_RolloutStrategy(a.(*v1beta1.RolloutStrategy), b.(*RolloutStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosControlPlane)(nil), (*v1beta1.TalosControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(a.(*TalosControlPlane), b.(*v1beta1.TalosControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosControlPlane)(nil), (*TalosControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(a.(*v1beta1.TalosControlPlane), b.(*TalosControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosControlPlaneList)(nil), (*v1beta1.TalosControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList(a.(*TalosControlPlaneList), b.(*v1beta1.TalosControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosControlPlaneList)(nil), (*TalosControlPlaneList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList(a.(*v1beta1.TalosControlPlaneList), b.(*TalosControlPlaneList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1.ObjectReference)(nil), (*v1beta2.ContractVersionedObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ObjectReference_To_v1beta2_ContractVersionedObjectReference(a.(*corev1.ObjectReference), b.(*v1beta2.ContractVersionedObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TalosControlPlaneSpec)(nil), (*v1beta1.TalosControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec(a.(*TalosControlPlaneSpec), b.(*v1beta1.TalosControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TalosControlPlaneStatus)(nil), (*v1beta1.TalosControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosControlPlaneStatus_To_v1beta1_TalosControlPlaneStatus(a.(*TalosControlPlaneStatus), b.(*v1beta1.TalosControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*corev1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.TalosControlPlaneSpec)(nil), (*TalosControlPlaneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec(a.(*v1beta1.TalosControlPlaneSpec), b.(*TalosControlPlaneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.TalosControlPlaneStatus)(nil), (*TalosControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosControlPlaneStatus_To_v1alpha3_TalosControlPlaneStatus(a.(*v1beta1.TalosControlPlaneStatus), b.(*TalosControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.ContractVersionedObjectReference)(nil), (*corev1.ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ContractVersionedObjectReference_To_v1_ObjectReference(a.(*v1beta2.ContractVersionedObjectReference), b.(*corev1.ObjectReference), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig(in *ControlPlaneConfig, out *v1beta1.ControlPlaneConfig, s conversion.Scope) error {
	out.InitConfig = in.InitConfig
	out.ControlPlaneConfig = in.ControlPlaneConfig
	return nil
}

// Convert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig(in *ControlPlaneConfig, out *v1beta1.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig(in *v1beta1.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.InitConfig = in.InitConfig
	out.ControlPlaneConfig = in.ControlPlaneConfig
	return nil
}

// Convert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig(in *v1beta1.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha3_RollingUpdate_To_v1beta1_RollingUpdate(in *RollingUpdate, out *v1beta1.RollingUpdate, s conversion.Scope) error {
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1alpha3_RollingUpdate_To_v1beta1_RollingUpdate is an autogenerated conversion function.
func Convert_v1alpha3_RollingUpdate_To_v1beta1_RollingUpdate(in *RollingUpdate, out *v1beta1.RollingUpdate, s conversion.Scope) error {
	return autoConvert_v1alpha3_RollingUpdate_To_v1beta1_RollingUpdate(in, out, s)
}

func autoConvert_v1beta1_RollingUpdate_To_v1alpha3_RollingUpdate(in *v1beta1.RollingUpdate, out *RollingUpdate, s conversion.Scope) error {
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1beta1_RollingUpdate_To_v1alpha3_RollingUpdate is an autogenerated conversion function.
func Convert_v1beta1_RollingUpdate_To_v1alpha3_RollingUpdate(in *v1beta1.RollingUpdate, out *RollingUpdate, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpdate_To_v1alpha3_RollingUpdate(in, out, s)
}

func autoConvert_v1alpha3_RolloutStrategy_To_v1beta1_RolloutStrategy(in *RolloutStrategy, out *v1beta1.RolloutStrategy, s conversion.Scope) error {
	out.RollingUpdate = (*v1beta1.RollingUpdate)(unsafe.Pointer(in.RollingUpdate))
	out.Type = v1beta1.RolloutStrategyType(in.Type)
	return nil
}

// Convert_v1alpha3_RolloutStrategy_To_v1beta1_RolloutStrategy is an autogenerated conversion function.
func Convert_v1alpha3_RolloutStrategy_To_v1beta1_RolloutStrategy(in *RolloutStrategy, out *v1beta1.RolloutStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha3_RolloutStrategy_To_v1beta1_RolloutStrategy(in, out, s)
}

func autoConvert_v1beta1_RolloutStrategy_To_v1alpha3_RolloutStrategy(in *v1beta1.RolloutStrategy, out *RolloutStrategy, s conversion.Scope) error {
	out.RollingUpdate = (*RollingUpdate)(unsafe.Pointer(in.RollingUpdate))
	out.Type = RolloutStrategyType(in.Type)
	return nil
}

// Convert_v1beta1_RolloutStrategy_To_v1alpha3_RolloutStrategy is an autogenerated conversion function.
func Convert_v1beta1_RolloutStrategy_To_v1alpha3_RolloutStrategy(in *v1beta1.RolloutStrategy, out *RolloutStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RolloutStrategy_To_v1alpha3_RolloutStrategy(in, out, s)
}

func autoConvert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(in *TalosControlPlane, out *v1beta1.TalosControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_TalosControlPlaneStatus_To_v1beta1_TalosControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane is an autogenerated conversion function.
func Convert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(in *TalosControlPlane, out *v1beta1.TalosControlPlane, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(in, out, s)
}

func autoConvert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(in *v1beta1.TalosControlPlane, out *TalosControlPlane, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TalosControlPlaneStatus_To_v1alpha3_TalosControlPlaneStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane is an autogenerated conversion function.
func Convert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(in *v1beta1.TalosControlPlane, out *TalosControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(in, out, s)
}

func autoConvert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList(in *TalosControlPlaneList, out *v1beta1.TalosControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.TalosControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_TalosControlPlane_To_v1beta1_TalosControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList is an autogenerated conversion function.
func Convert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList(in *TalosControlPlaneList, out *v1beta1.TalosControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosControlPlaneList_To_v1beta1_TalosControlPlaneList(in, out, s)
}

func autoConvert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList(in *v1beta1.TalosControlPlaneList, out *TalosControlPlaneList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosControlPlane, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_TalosControlPlane_To_v1alpha3_TalosControlPlane(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList is an autogenerated conversion function.
func Convert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList(in *v1beta1.TalosControlPlaneList, out *TalosControlPlaneList, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosControlPlaneList_To_v1alpha3_TalosControlPlaneList(in, out, s)
}

func autoConvert_v1alpha3_TalosControlPlaneSpec_To_v1beta1_TalosControlPlaneSpec(in *TalosControlPlaneSpec, out *v1beta1.TalosControlPlaneSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	// WARNING: in.InfrastructureTemplate requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha3_ControlPlaneConfig_To_v1beta1_ControlPlaneConfig(&in.ControlPlaneConfig, &out.ControlPlaneConfig, s); err != nil {
		return err
	}
	out.RolloutStrategy = (*v1beta1.RolloutStrategy)(unsafe.Pointer(in.RolloutStrategy))
	return nil
}

func autoConvert_v1beta1_TalosControlPlaneSpec_To_v1alpha3_TalosControlPlaneSpec(in *v1beta1.TalosControlPlaneSpec, out *TalosControlPlaneSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Version = in.Version
	// WARNING: in.MachineTemplate requires manual conversion: does not exist in peer-type
	// WARNING: in.MachineNamingStrategy requires manual conversion: does not exist in peer-type
	if err := Convert_v1beta1_ControlPlaneConfig_To_v1alpha3_ControlPlaneConfig(&in.ControlPlaneConfig, &out.ControlPlaneConfig, s); err != nil {
		return err
	}
	out.RolloutStrategy = (*RolloutStrategy)(unsafe.Pointer(in.RolloutStrategy))
	return nil
}

func autoConvert_v1alpha3_TalosControlPlaneStatus_To_v1beta1_TalosControlPlaneStatus(in *TalosControlPlaneStatus, out *v1beta1.TalosControlPlaneStatus, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	// WARNING: in.UnavailableReplicas requires manual conversion: does not exist in peer-type
	// WARNING: in.Initialized requires manual conversion: does not exist in peer-type
	// WARNING: in.Ready requires manual conversion: does not exist in peer-type
	out.Bootstrapped = in.Bootstrapped
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	out.Version = (*string)(unsafe.Pointer(in.Version))
	// WARNING: in.V1Beta2 requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_TalosControlPlaneStatus_To_v1alpha3_TalosControlPlaneStatus(in *v1beta1.TalosControlPlaneStatus, out *TalosControlPlaneStatus, s conversion.Scope) error {
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	out.Selector = in.Selector
	out.Replicas = in.Replicas
	out.ReadyReplicas = in.ReadyReplicas
	// WARNING: in.AvailableReplicas requires manual conversion: does not exist in peer-type
	// WARNING: in.UpToDateReplicas requires manual conversion: does not exist in peer-type
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.ObservedGeneration = in.ObservedGeneration
	out.Bootstrapped = in.Bootstrapped
	// WARNING: in.Deprecated requires manual conversion: does not exist in peer-type
	return nil
}
